esphome:
  name: 'vitowifi'
  friendly_name: 'VitoWiFi'
esp8266:
  board: d1_mini

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  domain: .fritz.box
  manual_ip:
    static_ip: 192.168.178.101
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1

api:
  encryption:
    key: !secret esphome_api_key

logger:
#  level: INFO
  baud_rate: 0 

uart:
  tx_pin: GPIO1   # TX (Hardware UART)
  rx_pin: GPIO3   # RX (Hardware UART)
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 2

optolink:
  protocol: P300

ota:
  - platform: esphome
    password: !secret esphome_api

external_components:
#  - source: components
#  - source: github://pr#4453
#    components: [ optolink ]
  - source: github://j0ta29/esphome@optolink
    components: [optolink]

sensor:
  - platform: optolink
    name: Brennerstarts
    address: 0x088A
    bytes: 4
    icon: "mdi:ray-start-arrow"
  - platform: optolink
    name: Kesseltemperatur
    address: 0x0802
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
  - platform: optolink
    name: Aussentemperatur
    address: 0x0800
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
    icon: "mdi:sun-thermometer"
  - platform: optolink
    name: Speichertemperatur
    address: 0x0804
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
    icon: "mdi:water-thermometer"
  - platform: optolink
    name: Betriebsstunden
    id: betrieb
    address: 0x8A7
    bytes: 4
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 60s 
    icon: "mdi:clock-start"
    filters:
      - lambda: return x / 3600.0;
  - platform: uptime
    name: Uptime Sensor
    update_interval: 60min
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60min
  
binary_sensor:
   - platform: optolink
     name: Störung
     address: 0x0A82
     icon: "mdi:alarm-light"
   - platform: optolink
     name: Brenner Status
     address: 0x0842 #0x55D3
     icon: "mdi:gas-burner"
   - platform: optolink
     name: Partybetrieb Status
     address: 0x2303
     icon: "mdi:party-popper"
   - platform: optolink
     name: Sparbetrieb Status
     address: 0x2302
     icon: mdi:snowflake-alert

number:
  - platform: optolink
    name: Raumtemperatur Soll
    unit_of_measurement: °C
    address: 0x2306
    bytes: 1
    min_value: 10
    max_value: 28
    step: 1
    mode: box
    icon: "mdi:home-thermometer"
    device_class: temperature
  - platform: optolink
    name: Speichertemperatur Soll
    unit_of_measurement: °C
    address: 0x6300
    bytes: 1
    min_value: 35
    max_value: 70
    step: 1
    mode: box
    icon: "mdi:water-thermometer"
    device_class: temperature

select:
  - platform: optolink
    name: Betriebsart
    address: 0x2323
    bytes: 1
    map:
      - "0 -> Aus"
      - "1 -> nur Warmwasser"
      - "2 -> Heizen und Warmwasser"

switch:
  - platform: optolink
    id: Partybetrieb_sw
    name: Partybetrieb
    address: 0x2330
    icon: mdi:party-popper
  - platform: optolink
    id: sparbetrieb_sw
    name: Sparbetrieb
    address: 0x2331
    icon: mdi:snowflake-alert
  
button:
  - platform: restart
    name: "Restart"
  - platform: shutdown
    name: "Shutdown"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
#    ssid:
#      name: "SSID"
    mac_address:
      name: "Mac"
#  - platform: optolink
#    name: Error history 1
#    address: 0x7590
#    bytes: 9
#    raw: true
time:
  - platform: homeassistant
    id: homeassistant_time
