substitutions:
  my_name: VitoWiFi
  divicename: vitowifi

external_components:
  - source: components
#  - source: github://pr#4453
#    components: [ optolink ]
esphome:
  name: vitowifi
  friendly_name: $my_name
  platform: ESP8266
  board: d1_mini

optolink:
  protocol: P300
  device_info: Device Info
  #state: Component state

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .fritz.box
  manual_ip:
    static_ip: 192.168.178.91
    gateway: 192.168.178.1
    subnet: 255.255.255.0
    dns1: 192.168.178.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "VitoWiFiHotspot"
    password: "!secret VitoWiFiHotspot"

api:
  encryption:
    key: !secret esphome_api_key
# Enable logging
logger:
  hardware_uart: UART0
  baud_rate: 0 
#  level: DEBUG

ota:
  - platform: esphome
    password: !secret esphome_api

sensor:
  - platform: optolink
    name: Brennerstarts
    address: 0x088A
    bytes: 4
    icon: "mdi:ray-start-arrow"
  - platform: optolink
    name: Kesseltemperatur
    address: 0x0802
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
  - platform: optolink
    name: Aussentemperatur
    address: 0x0800
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
    icon: "mdi:sun-thermometer"
  - platform: optolink
    name: Speichertemperatur
    address: 0x0804
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature
    update_interval: 60s
    icon: "mdi:water-thermometer"
  - platform: optolink
    name: Betriebsstunden
    id: betrieb
    address: 0x8A7
    bytes: 4
    unit_of_measurement: "h"
    accuracy_decimals: 1
    update_interval: 60s 
    icon: "mdi:clock-start"
    filters:
      - lambda: return x / 3600.0;
# Uptime Sensor - Zeit seit letztem rebbot
  - platform: uptime
    name: Uptime Sensor
    update_interval: 60s

# Ermittlung der WLAN-Signalstärke alle 60s 
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s

binary_sensor:
   - platform: optolink
     name: Störung
     address: 0x0A82
     icon: "mdi:alarm-light"
   - platform: optolink
     name: Brenner Status
     address: 0x0842 #0x55D3
     icon: "mdi:gas-burner"
   - platform: optolink
     name: Partybetrieb Status
     address: 0x2303
     icon: "mdi:party-popper"
   - platform: optolink
     name: Sparbetrieb Status
     address: 0x2302
     icon: mdi:snowflake-alert

number:
  - platform: optolink
    name: Raumtemperatur Soll
    unit_of_measurement: °C
    address: 0x2306
    bytes: 1
    min_value: 3
    max_value: 28
    step: 1
    mode: box
    icon: "mdi:home-thermometer"
    device_class: temperature
  - platform: optolink
    name: Speichertemperatur Soll
    unit_of_measurement: °C
    address: 0x6300
    bytes: 1
    min_value: 30
    max_value: 70
    step: 1
    mode: box
    icon: "mdi:water-thermometer"
    device_class: temperature

select:
  - platform: optolink
    name: Betriebsart
    address: 0x2323
    bytes: 1
    map:
      - "0 -> Aus"
      - "1 -> nur Warmwasser"
      - "2 -> Heizen und Warmwasser"
  - platform: optolink
    name: Partybetrieb
    icon: mdi:party-popper
    address: 0x2330
    bytes: 1
    map:
      - "0 -> Aus"
      - "1 -> Partybetrieb"
  - platform: optolink
    name: Sparbetrieb
    icon: mdi:snowflake-alert
    address: 0x2331
    bytes: 1
    map:
      - "0 -> Aus"
      - "1 -> Sparbetrieb"

# Button definition
button:
# Neustart ESP
  - platform: restart
    name: "Restart"
# Herunterfahren ESP
  - platform: shutdown
    name: "Shutdown"

# Text Sensor definition
# WIFI Info Bereich
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
#    ssid:
#      name: "SSID"
    mac_address:
      name: "Mac"
#  - platform: optolink
#    name: Error history 1
#    address: 0x7590
#    bytes: 9
#    raw: true
time:
  - platform: homeassistant
    id: homeassistant_time
